export default ({
  i: [{ random: 'cv' }, '代', '述詞', '自稱'],
  thou: [{ random: 'cv' }, '代', '述詞', '對稱'],
  he: [{ random: 'cv' }, '代', '述詞', '他稱'],
  what: [{ random: 'cv' }, '代', '述詞', '何'],
  self: [{ random: 'cv' }, '代', '述詞', '自身'],
  this: [{ random: 'cv' }, '代', '述詞', 'この發話'],

  that: [{ random: 'cv' }, '構造', '文→述', 'aはxである事である'],
  quote: [{ random: 'cv' }, '構造', '借用→述', 'aはxと呼ばれる'],
  verb: [{ random: 'cv' }, '構造', '', '動詞構造開'],
  end: [{ random: 'cv' }, '構造', '', '構造閉'],

  adverb: [{ random: 'cv' }, '格', '格詞', '副詞化'],
  object: [{ random: 'cv' }, '格', '格詞', 'を'],
  with: [{ random: 'cv' }, '格', '格詞', ''],
  passive: [{ random: 'cv' }, '構造', '述詞→述詞', '‘aはbをxする’↦bはaをxする'],

  not: [{ random: 'cv' }, '論理', '', ''],
  and: [{ random: 'cv' }, '論理', '', ''],
  unrestrictive: [{ random: 'cv' }, '', '', '非制限用法'],
  habitual: [{ random: 'cv' }, '', '', '非制限用法'],

  zero: [{ random: 'ccv' }, '數字', '數詞', '0'],
  one: [{ random: 'ccv' }, '數字', '數詞', '1'],
  two: [{ random: 'ccv' }, '數字', '數詞', '2'],
  three: [{ random: 'ccv' }, '數字', '數詞', '3'],
  four: [{ random: 'ccv' }, '數字', '數詞', '4'],
  five: [{ random: 'ccv' }, '數字', '數詞', '5'],
  six: [{ random: 'ccv' }, '數字', '數詞', '6'],
  seven: [{ random: 'ccv' }, '數字', '數詞', '7'],
  eight: [{ random: 'ccv' }, '數字', '數詞', '8'],
  nine: [{ random: 'ccv' }, '數字', '數詞', '9'],

  exp: [{ random: 'cv' }, '數字', '數詞', 'E'],

  null: [{ random: 'ccv' }, '特殊數字', '數詞', '無'],
  min: [{ random: 'ccv' }, '特殊數字', '數詞', '最小'],
  median: [{ random: 'ccv' }, '特殊數字', '數詞', '中央値'],
  more: [{ random: 'ccv' }, '特殊數字', '數詞', 'aより多い'],
  every: [{ random: 'ccv' }, '特殊數字', '數詞', '最大'],

  aleph0: [{ random: 'ccv' }, '特殊數字', '無限', '可算無限'],
  aleph1: [{ random: 'ccv' }, '特殊數字', '無限', '非可算無限'],

  tau: [{ random: 'ccv' }, '定數', '數詞', 'τ=6.283+ε'],
  napier: [{ random: 'ccv' }, '定數', '數詞', 'e=2.718+ε'],

  normal: [{ random: 'ccv' }, '特殊數字', '數詞', '通常の'],
  much_more: [{ random: 'ccv' }, '特殊數字', '數詞', 'xよりかなり大きい'],

  plus: [{ random: 'ccv' }, '演算', '數詞', '+'],
  minus: [{ random: 'ccv' }, '演算', '數詞', '-'],
  multiply: [{ random: 'ccv' }, '演算', '數詞', '*'],
  divide: [{ random: 'ccv' }, '演算', '數詞', '/'],
  modulo: [{ random: 'ccv' }, '演算', '數詞', '%'],
  power: [{ random: 'ccv' }, '演算', '數詞', '^'],
  logarithm: [{ random: 'ccv' }, '演算', '數詞', 'log'],

  ordinal: [{ random: 'ccv' }, '數字', '數→述', 'aはx番目である'],

  reverse: [{ random: 'cv' }, '', '述詞', 'aはbの逆である'],

  at: [{ random: 'cvc' }, '格', '述詞', 'aは所在bに有る'],
  from: [{ random: 'cvc' }, '格', '述詞', 'aはbを起點とする'],
  via: [{ random: 'cvc' }, '格', '述詞', 'aはbを經路とする'],

  above: [{ random: 'cvc' }, '位置關係', '述詞', 'aはbの上に有る'],
  front: [{ random: 'cvc' }, '位置關係', '述詞', 'aはbの前に有る'],
  left: [{ random: 'cvc' }, '位置關係', '述詞', 'aはbの左に有る'],
  before: [{ random: 'cvc' }, '位置關係', '述詞', 'aはbの未來に有る'],
  inside: [{ random: 'cvc' }, '位置關係', '述詞', 'aはbの中に有る'],

  cover: [{ random: 'cvc' }, '位置關係/複雜', '述詞', 'aはbを覆ふ'],
  far: [{ random: 'cvc' }, '位置關係/複雜', '述詞', 'aはbから（#距離）遠い'],
  cross: [{ random: 'cvc' }, '位置關係/複雜', '述詞', 'aはbに交叉する'],
  orthogonal: [{ random: 'cvc' }, '位置關係/複雜', '述詞', 'aはbに直交する'],
  parallel: [{ random: 'cvc' }, '位置關係/複雜', '述詞', 'aはbに平行する'],

  point: [{ random: 'cvc' }, '數學', '述詞', 'aは點である'],
  line: [{ random: 'cvc' }, '數學', '述詞', 'aは線である'],
  plane: [{ random: 'cvc' }, '數學', '述詞', 'aは平面である'],
  polygon: [{ random: 'cvc' }, '數學', '述詞', 'aは多面體である'],
  sharp: [{ random: 'cvc' }, '數學', '述詞', 'aは角である'],
  centre: [{ random: 'cvc' }, '數學', '述詞', 'aはbの中心である'],
  interval: [{ random: 'cvc' }, '數學', '述詞', 'aは區間である'],
  function: [{ random: 'cvc' }, '數學', '述詞', 'aは函數である'],

  space: [{ random: 'cvc' }, '物理', '述詞', 'aは空間である'],
  time: [{ random: 'cvc' }, '物理', '述詞', 'aは時間である'],
  wave: [{ random: 'cvc' }, '物理', '述詞', 'aは波である'],
  light: [{ random: 'cvc' }, '物理', '述詞', 'aは光である'],
  sound: [{ random: 'cvc' }, '物理', '述詞', 'aは音である'],
  reflect: [{ random: 'cvc' }, '物理', '述詞', 'aはbを反射する'],

  elementary_particle: [{ random: 'cvc' }, '物理/粒子', '述詞', '素粒子'],
  electron: [{ random: 'cvc' }, '物理/粒子', '述詞', '電子'],
  atom: [{ random: 'cvc' }, '物理/粒子', '述詞', '原子'],
  molecule: [{ random: 'cvc' }, '物理/粒子', '述詞', '分子'],

  solid: [{ random: 'cvc' }, '物理/態', '述詞', '固體'],
  liquid: [{ random: 'cvc' }, '物理/態', '述詞', '液體'],
  gas: [{ random: 'cvc' }, '物理/態', '述詞', '氣體'],
  plasma: [{ random: 'cvc' }, '物理/態', '述詞', 'plasma'],

  salt: [{ random: 'cvc' }, '化學', '述詞', 'aは鹽である'],
  oil: [{ random: 'cvc' }, '化學', '述詞', 'aは油脂である'],

  colour: [{ random: 'cvc' }, '色', '述詞', 'aはbの呈する色である'],
  bright: [{ random: 'cvc' }, '色', '述詞', 'aは明るい'],
  colourful: [{ random: 'cvc' }, '色', '述詞', 'aは高彩度である'],
  red: [{ random: 'cvc' }, '色', '述詞', 'aは赤い'],
  orange: [{ random: 'cvc' }, '色', '述詞', 'aは橙色を呈する'],
  yellow: [{ random: 'cvc' }, '色', '述詞', 'aは黄色を呈する'],
  green: [{ random: 'cvc' }, '色', '述詞', 'aは綠色を呈する'],
  blue: [{ random: 'cvc' }, '色', '述詞', 'aは青い'],
  purple: [{ random: 'cvc' }, '色', '述詞', 'aは紫色を呈する'],

  universe: [{ random: 'cvc' }, '宇宙', '述詞', '宇宙'],
  star: [{ random: 'cvc' }, '宇宙', '述詞', '恆星'],
  planet: [{ random: 'cvc' }, '宇宙', '述詞', '惑星'],
  sattelite: [{ random: 'cvc' }, '宇宙', '述詞', '衞星'],

  land: [{ random: 'cvc' }, '地理', '述詞', '陸'],
  sky: [{ random: 'cvc' }, '地理', '述詞', '空'],
  mountain: [{ random: 'cvc' }, '地理', '述詞', '山'],
  sea: [{ random: 'cvc' }, '地理', '述詞', '海'],
  lake: [{ random: 'cvc' }, '地理', '述詞', '湖'],
  river: [{ random: 'cvc' }, '地理', '述詞', '川'],

  male: [{ random: 'cvc' }, '性', '述詞', 'aは雄である'],
  female: [{ random: 'cvc' }, '性', '述詞', 'aは雌である'],
  copulate: [{ random: 'cvc' }, '性', '述詞', 'aはbと交接する'],

  human: [{ random: 'cvc' }, '生物', '述詞', 'aは人である'],
  animal: [{ random: 'cvc' }, '生物', '述詞', 'aは動物である'],
  plant: [{ random: 'cvc' }, '生物', '述詞', 'aは植物である'],

  hair: [{ random: 'cvc' }, '身體/頭', '述詞', 'aはbの毛である'],
  brain: [{ random: 'cvc' }, '身體/頭', '述詞', 'aはbの腦である'],
  eye: [{ random: 'cvc' }, '身體/頭', '述詞', 'aはbの目である'],
  ear: [{ random: 'cvc' }, '身體/頭', '述詞', 'aはbの耳である'],
  nose: [{ random: 'cvc' }, '身體/頭', '述詞', 'aはbの鼻である'],
  mouth: [{ random: 'cvc' }, '身體/頭', '述詞', 'aはbの口である'],
  tooth: [{ random: 'cvc' }, '身體/頭', '述詞', 'aはbの齒（牙）である'],
  tongue: [{ random: 'cvc' }, '身體/頭', '述詞', 'aはbの舌である'],
  throat: [{ random: 'cvc' }, '身體/頭', '述詞', 'aはbの喉である'],
  horn: [{ random: 'cvc' }, '身體/頭', '述詞', 'aはbの角である'],

  heart: [{ random: 'cvc' }, '身體/内臓', '述詞', 'aはbの心臓である'],
  lung: [{ random: 'cvc' }, '身體/内臓', '述詞', 'aはbの肺である'],
  gut: [{ random: 'cvc' }, '身體/内臓', '述詞', 'aはbの消化管である'],

  trunk: [{ random: 'cvc' }, '身體/胴', '述詞', 'aはbの胴（幹）である'],
  tail: [{ random: 'cvc' }, '身體/胴', '述詞', 'aはbの尾である'],
  ass: [{ random: 'cvc' }, '身體/胴', '述詞', 'aはbの臀部である'],
  penis: [{ random: 'cvc' }, '身體/胴', '述詞', 'aはbの陰莖（陰核）である'],
  womb: [{ random: 'cvc' }, '身體/胴', '述詞', 'aはbの子宮である'],
  nipple: [{ random: 'cvc' }, '身體/胴', '述詞', 'aはbの乳首である'],

  limb: [{ random: 'cvc' }, '身體/肢', '述詞', 'aはbの肢（腕・脚・枝・翼）である'],
  hand: [{ random: 'cvc' }, '身體/肢', '述詞', 'aはbの手足である'],
  finger: [{ random: 'cvc' }, '身體/肢', '述詞', 'aはbの指である'],
  nail: [{ random: 'cvc' }, '身體/肢', '述詞', 'aはbの爪である'],

  nerve: [{ random: 'cvc' }, '身體/全身', '述詞', 'aはbの神經である'],
  muscle: [{ random: 'cvc' }, '身體/全身', '述詞', 'aはbの肉である'],
  bone: [{ random: 'cvc' }, '身體/全身', '述詞', 'aはbの骨である'],
  skin: [{ random: 'cvc' }, '身體/全身', '述詞', 'aはbの肌である'],

  fruit: [{ random: 'cvc' }, '身體/植物', '述詞', 'aはbの果實である'],
  root: [{ random: 'cvc' }, '身體/植物', '述詞', 'aはbの根である'],

  eat: [{ random: 'cvc' }, '生理', '述詞', 'aはbを食ふ'],
  digest: [{ random: 'cvc' }, '生理', '述詞', 'aはbを消化する'],
  excrete: [{ random: 'cvc' }, '生理', '述詞', 'aはbを排泄する'],

  sense: [{ random: 'cvc' }, '感覺', '述詞', 'aはbを感ず'],
  hear: [{ random: 'cvc' }, '感覺', '述詞', 'aはbを聞く'],
  see: [{ random: 'cvc' }, '感覺', '述詞', 'aはbを見る'],
  taste: [{ random: 'cvc' }, '感覺', '述詞', 'aはbの味を感ず'],
  smell: [{ random: 'cvc' }, '感覺', '述詞', 'aはbの匂ひを感ず'],
  touch: [{ random: 'cvc' }, '感覺', '述詞', 'aはbを觸感す'],
  hurt: [{ random: 'cvc' }, '感覺', '述詞', 'aはbに痛む'],

  smile: [{ random: 'cvc' }, '表情', '述詞', 'aは微笑する'],
  laugh: [{ random: 'cvc' }, '表情', '述詞', 'aは笑ふ'],
  frown: [{ random: 'cvc' }, '表情', '述詞', 'aは顔を顰める'],
  cry: [{ random: 'cvc' }, '表情', '述詞', 'aはb（涙）を流す'],

  want: [{ random: 'cvc' }, '感情', '述詞', 'aはbを求める'],
  glad: [{ random: 'cvc' }, '感情', '述詞', 'aはbを喜ぶ'],
  amuse: [{ random: 'cvc' }, '感情', '述詞', 'aはbを樂しむ'],
  respect: [{ random: 'cvc' }, '感情', '述詞', 'aはbを敬ふ'],
  proud: [{ random: 'cvc' }, '感情', '述詞', 'aはbを誇る'],
  amaze: [{ random: 'cvc' }, '感情', '述詞', 'aはbに驚く'],
  angry: [{ random: 'cvc' }, '感情', '述詞', 'aはbに怒る'],

  think: [{ random: 'cvc' }, '思考', '述詞', 'aはbを思ふ'],
  know: [{ random: 'cvc' }, '思考', '述詞', 'aはbを知る'],
  understand: [{ random: 'cvc' }, '思考', '述詞', 'aはbを理解する'],
  assume: [{ random: 'cvc' }, '思考', '述詞', 'aはbを假定する'],
  plan: [{ random: 'cvc' }, '思考', '述詞', 'aはbを意圖する'],
  expect: [{ random: 'cvc' }, '思考', '述詞', 'aはbを豫期する'],
  hope: [{ random: 'cvc' }, '思考', '述詞', 'aはbを希望する'],
  agree: [{ random: 'cvc' }, '思考', '述詞', 'aはbに同意する'],
  deduce: [{ random: 'cvc' }, '思考', '述詞', 'aはbを推理する'],

  output: [{ random: 'cvc' }, '出力', '述詞', 'aはbを出力する'],
  speak: [{ random: 'cvc' }, '出力', '述詞', 'aはbを話す'],
  write: [{ random: 'cvc' }, '出力', '述詞', 'aはbを書く'],

  declare: [{ random: 'cvc' }, '行動', '述詞', 'aはbを宣言する'],
  ask: [{ random: 'cvc' }, '行動', '述詞', 'aはbを質問する'],
  greet: [{ random: 'cvc' }, '行動', '述詞', 'aは挨拶する'],
  apologise: [{ random: 'cvc' }, '行動', '述詞', 'aは謝る'],
  appreciate: [{ random: 'cvc' }, '行動', '述詞', 'aは感謝する'],
  forgive: [{ random: 'cvc' }, '行動', '述詞', 'aは許す'],

  play: [{ random: 'cvc' }, '文化', '述詞', 'aはbを遊ぶ'],
  dance: [{ random: 'cvc' }, '文化', '述詞', 'aはbを踊る'],
  music: [{ random: 'cvc' }, '文化', '述詞', 'aはbを演奏する'],
  intercourse: [{ random: 'cvc' }, '文化', '述詞', 'aは性行爲する'],

  building: [{ random: 'cvc' }, '文明', '述詞', '建造物'],
  town: [{ random: 'cvc' }, '文明', '述詞', '町'],
  nation: [{ random: 'cvc' }, '文明', '述詞', '國'],
  group: [{ random: 'cvc' }, '文明', '述詞', 'aはbを目的とするの集團（會） である'],

  world: [{ random: 'cvc' }, '', '述詞', 'aは世界である'],
  true: [{ random: 'cvc' }, '', '述詞', 'aは眞である'],
  have: [{ random: 'cvc' }, '', '述詞', 'aはbを有す'],
  cause: [{ random: 'cvc' }, '', '述詞', 'aはbを起こす'],
  begin: [{ random: 'cvc' }, '', '述詞', 'aは始める'],
  person: [{ random: 'cvc' }, '', '述詞', 'aは自我を持つ'],
  alive: [{ random: 'cvc' }, '', '述詞', 'aは生きる'],
  depend: [{ random: 'cvc' }, '', '述詞', 'aはbに影響する'],
  open: [{ random: 'cvc' }, '', '述詞', 'aはbを開く'],
  home: [{ random: 'cvc' }, '', '述詞', 'aはbの據點である'],
  fight: [{ random: 'cvc' }, '', '述詞', 'aはbに抗ふ'],
  deceive: [{ random: 'cvc' }, '', '述詞', 'aはbであると欺く'],
  wake: [{ random: 'cvc' }, '', '述詞', 'aは覺める'],
  consume: [{ random: 'cvc' }, '', '述詞', 'aはbを費やす'],
  old: [{ random: 'cvc' }, '', '述詞', 'aは古い'],
  long: [{ random: 'cvc' }, '', '述詞', 'aは長い'],
  big: [{ random: 'cvc' }, '', '述詞', 'aは大きい'],
  differ: [{ random: 'cvc' }, '', '述詞', 'aはbと異なる'],
  worth: [{ random: 'cvc' }, '', '述詞', 'aはbに値する'],
  get: [{ random: 'cvc' }, '', '述詞', 'aはbを得る'],
  make: [{ random: 'cvc' }, '', '述詞', 'aはbを作る'],
  contain: [{ random: 'cvc' }, '', '述詞', 'aはbの要素である'],
  leave: [{ random: 'cvc' }, '', '述詞', 'aはbから去る'],
  use: [{ random: 'cvc' }, '', '述詞', 'aはbを使ふ'],
  status: [{ random: 'cvc' }, '', '述詞', 'aはbの狀態である'],
  manner: [{ random: 'cvc' }, '', '述詞', 'aはbの樣態である'],
  rot: [{ random: 'cvc' }, '', '述詞', 'aは腐る'],
  influence: [{ random: 'cvc' }, '', '述詞', 'aはbに影響する'],
  risk: [{ random: 'cvc' }, '', '述詞', 'aはbの危機である'],
  rotate: [{ random: 'cvc' }, '', '述詞', 'aは回轉する'],
  temporary: [{ random: 'cvc' }, '', '述詞', 'aは一時的である'],
  map: [{ random: 'cvc' }, '', '述詞', 'aはbの地圖である'],
  imitate: [{ random: 'cvc' }, '', '述詞', 'aはbを模倣する'],
})