export const letters = {
  a: { name: 'hela', cyrl: 'а' },
  b: { name: 'ba', cyrl: 'б' },
  c: { name: 'ca', cyrl: 'г' },
  d: { name: 'da', cyrl: 'д' },
  e: { name: 'le', cyrl: 'є' },
  f: { name: 'fa', cyrl: 'ф' },
  g: { name: 'ga', cyrl: 'ң' },
  h: { name: 'ha', cyrl: 'х' },
  i: { name: 'li', cyrl: 'i' },
  j: { name: 'ja', cyrl: 'ж' },
  k: { name: 'ka', cyrl: 'к' },
  l: { name: 'la', cyrl: 'л' },
  m: { name: 'ma', cyrl: 'м' },
  n: { name: 'na', cyrl: 'н' },
  o: { name: 'lo', cyrl: 'о' },
  p: { name: 'pa', cyrl: 'п' },
  q: { name: 'qa', cyrl: 'ҁ' },
  ø: { name: 'rø', cyrl: 'ю' },
  s: { name: 'sa', cyrl: 'с' },
  t: { name: 'ta', cyrl: 'т' },
  u: { name: 'lu', cyrl: 'у' },
  v: { name: 'va', cyrl: 'в' },
  w: { name: 'lw', cyrl: 'ъ' },
  x: { name: 'xa', cyrl: 'ш' },
  y: { name: 'ly', cyrl: 'ѵ' },
  z: { name: 'za', cyrl: 'з' },
}

export const dictBase = {
  _language: { name: 'CVCVCV', category: '', type: '動', named: 'Aはこの言語である', version: 0, etymology: '' },

  comma: { name: 'CV', category: '', type: '', named: '', version: 0, etymology: '' },
  period: { name: 'CV', category: '', type: '', named: '', version: 0, etymology: '' },

  about: { name: 'fa', category: '', type: '', named: '', version: 0, etymology: 'Jpn は' },
  der: { name: 'de', category: '', type: '', named: '', version: 0, etymology: 'Deu der' },
  den: { name: 'la', category: '', type: '', named: '', version: 0, etymology: 'Fas را' },
  _swap: { name: 'ta', category: '', type: '', named: '', version: 0, etymology: 'Fin -taan' },
  of: { name: 'no', category: '', type: '', named: '', version: 0, etymology: 'Jpn の' },

  _tense: { name: 'CV', category: '', type: '', named: '-:過去, type: 0:現在, +:未來', version: 0, etymology: '' },
  _aspect: { name: 'CV', category: '', type: '', named: 'min:開始, max:完了', version: 0, etymology: '' },

  do: { name: 'xa', category: '', type: '', named: '', version: 0, etymology: 'Ltc 者' },
  as: { name: 'CV', category: '', type: '', named: '', version: 0, etymology: '' },

  i: { name: 'va', category: '代', type: '動', named: 'われ', version: 0, etymology: 'Jpn わ' },
  thou: { name: 'ty', category: '代', type: '動', named: 'なれ', version: 0, etymology: 'french tu' },
  he: { name: 'si', category: '代', type: '動', named: '甲', version: 0, etymology: '' },
  he1: { name: 'se', category: '代', type: '動', named: '乙', version: 0, etymology: '' },
  he2: { name: 'sa', category: '代', type: '動', named: '丙', version: 0, etymology: '' },
  now: { name: 'CV', category: '代', type: '動', named: 'いま', version: 0, etymology: '' },
  here: { name: 'CV', category: '代', type: '動', named: 'ここ', version: 0, etymology: '' },
  something: { name: 'CV', category: '代', type: '動', named: '', version: 0, etymology: '' },

  what: { name: 'xu', category: '', type: '', named: '', version: 0, etymology: 'Ltc 誰' },
  that: { name: 'CV', category: '', type: '', named: '', version: 0, etymology: '' },
  whether: { name: 'CV', category: '', type: '', named: '', version: 0, etymology: '' },

  so_much: { name: 'CV', category: '代', type: '* 數: 量', named: '(X:數) ほど', version: 0, etymology: '' },
  how_much: { name: 'CV', category: '代', type: '量', named: '幾ら', version: 0, etymology: '' },

  _quote: { name: 'bi', category: '構造', type: '借用→動', named: 'AはXでありBを意味する', version: 0, etymology: '' },

  _insert: { name: 'xi', category: '構造', type: '', named: '', version: 0, etymology: '' },
  _insert_end: { name: 'xy', category: '構造', type: '', named: '', version: 0, etymology: '' },

  _past: { name: 'CV', category: '', type: '助動', named: '=WHAT NOW BEFORE-V AT', version: 0, etymology: '' },

  unrestrictive: { name: 'CV', category: '動→動', type: '', named: '非制限', version: 0, etymology: '' },
  typical: { name: 'CV', category: '動→動', type: '', named: '習慣', version: 0, etymology: '' },
  figurative: { name: 'CV', category: '動→動', type: '', named: '譬喩', version: 0, etymology: '' },

  zero: { name: 'li', category: '數字', type: '數詞', named: '0', version: 0, etymology: 'Cmn 零' },
  one: { name: 've', category: '數字', type: '數詞', named: '1', version: 0, etymology: 'PIE' },
  two: { name: 'da', category: '數字', type: '數詞', named: '2', version: 0, etymology: 'PIE' },
  three: { name: 'to', category: '數字', type: '數詞', named: '3', version: 0, etymology: 'PIE' },
  four: { name: 'qu', category: '數字', type: '數詞', named: '4', version: 0, etymology: 'PIE' },
  five: { name: 'pw', category: '數字', type: '數詞', named: '5', version: 0, etymology: 'PIE' },
  six: { name: 'sø', category: '數字', type: '數詞', named: '6', version: 0, etymology: 'PIE' },
  seven: { name: 'zy', category: '數字', type: '數詞', named: '7', version: 0, etymology: 'PIE' },
  eight: { name: 'ki', category: '數字', type: '數詞', named: '8', version: 0, etymology: 'PIE' },
  nine: { name: 'ne', category: '數字', type: '數詞', named: '9', version: 0, etymology: 'PIE' },
  ten: { name: 'ga', category: '數字', type: '數詞', named: '10', version: 0, etymology: '' },
  eleven: { name: 'Co', category: '數字', type: '數詞', named: '11', version: 0, etymology: '' },
  twelve: { name: 'Cu', category: '數字', type: '數詞', named: '12', version: 0, etymology: '' },
  thirteen: { name: 'Cw', category: '數字', type: '數詞', named: '13', version: 0, etymology: '' },
  fourteen: { name: 'Cø', category: '數字', type: '數詞', named: '14', version: 0, etymology: '' },
  fifteen: { name: 'Cy', category: '數字', type: '數詞', named: '15', version: 0, etymology: '' },

  exp: { name: 'CV', category: '數字/記號', type: '數詞', named: 'E', version: 0, etymology: '' },

  null: { name: 'CV', category: '特殊數字', type: '數詞', named: '無', version: 0, etymology: '' },
  min: { name: 'CV', category: '特殊數字', type: '數詞', named: '最小', version: 0, etymology: '' },
  max: { name: 'CV', category: '特殊數字', type: '數詞', named: '最大', version: 0, etymology: '' },

  at_most: { name: 'CV', category: '特殊數字/關係', type: '數詞', named: '≤', version: 0, etymology: '' },
  less_than: { name: 'CV', category: '特殊數字/關係', type: '數詞', named: '<', version: 0, etymology: '' },

  negative: { name: 'CV', category: '特殊數字', type: '數詞', named: '=LESS_THAN ZERO', version: 0, etymology: '' },
  positive: { name: 'CV', category: '特殊數字', type: '數詞', named: '=ZERO LESS_THAN', version: 0, etymology: '' },

  aleph0: { name: 'CV', category: '特殊數字', type: '無限', named: '可算無限', version: 0, etymology: '' },
  aleph1: { name: 'CV', category: '特殊數字', type: '無限', named: '非可算無限', version: 0, etymology: '' },

  tau: { name: 'CV', category: '定數', type: '數詞', named: 'τ=6.283+ε', version: 0, etymology: '' },
  napier: { name: 'CV', category: '定數', type: '數詞', named: 'e=2.718+ε', version: 0, etymology: '' },

  normal: { name: 'CV', category: '特殊數字', type: '數詞', named: '通常の', version: 0, etymology: '' },
  high: { name: 'CV', category: '特殊數字', type: '數詞', named: '[別名] MORE NORMAL', version: 0, etymology: '' },
  low: { name: 'CV', category: '特殊數字', type: '數詞', named: '[別名] PASSIVE MORE NORMAL', version: 0, etymology: '' },

  plus: { name: 'CV', category: '演算', type: '數詞', named: '+', version: 0, etymology: '' },
  minus: { name: 'CV', category: '演算', type: '數詞', named: '-', version: 0, etymology: '' },
  multiply: { name: 'CV', category: '演算', type: '數詞', named: '*', version: 0, etymology: '' },
  divide: { name: 'CV', category: '演算', type: '數詞', named: '/', version: 0, etymology: '' },
  modulo: { name: 'CV', category: '演算', type: '數詞', named: '%', version: 0, etymology: '' },
  power: { name: 'CV', category: '演算', type: '數詞', named: '^', version: 0, etymology: '' },
  logarithm: { name: 'CV', category: '演算', type: '數詞', named: 'log', version: 0, etymology: '' },

  ordinal: { name: 'CV', category: '數字', type: '(* (x: 數)): 動', named: 'Aはx番目である', version: 0, etymology: '' },

  not: { name: 'zi', category: '', type: '', named: '', version: 0, etymology: '' },
  and: { name: 'CV', category: '', type: '', named: '', version: 0, etymology: '' },
  or: { name: 'CV', category: '', type: '', named: '', version: 0, etymology: '' },
  imply: { name: 'CV', category: '', type: '', named: '', version: 0, etymology: '' },

  back: { name: 'CV', category: '', type: '動', named: 'AはBの逆である', version: 0, etymology: '' },

  have: { name: 'ha', category: '', type: '動', named: 'AをBは有す', version: 0, etymology: 'Lat habere' },
  give: { name: 'ce', category: '', type: '動', named: 'AをBは與ふ', version: 0, etymology: 'DGem gebaną' },
  take: { name: { alias: 'GIVE-BACK' }, category: '', type: '動', named: '受く', version: 0, etymology: '' },

  below: { name: 'CVCV', category: '位置關係', type: '動', named: 'AはBの下に有る', version: 0, etymology: '' },
  behind: { name: 'CVCV', category: '位置關係', type: '動', named: 'AはBの後に有る', version: 0, etymology: '' },
  left: { name: 'CVCV', category: '位置關係', type: '動', named: 'AはBの左に有る', version: 0, etymology: '' },
  before: { name: 'CVCV', category: '位置關係', type: '動', named: 'AはBの中に有る', version: 0, etymology: '' },
  in: { name: 'CVCV', category: '位置關係', type: '動', named: 'AはBの中に有る', version: 0, etymology: '' },

  far: { name: 'CVCV', category: '位置關係/複雜', type: '動', named: 'AはBから遠い', version: 0, etymology: '' },
  cross: { name: 'CVCV', category: '位置關係/複雜', type: '動', named: 'AはBに交叉する', version: 0, etymology: '' },
  orthogonal: { name: 'CVCV', category: '位置關係/複雜', type: '動', named: 'AはBに直交する', version: 0, etymology: '' },
  parallel: { name: 'CVCV', category: '位置關係/複雜', type: '動', named: 'AはBに平行する', version: 0, etymology: '' },

  big: { name: 'CVCV', category: '量', type: '動', named: 'Aは大きい', version: 0, etymology: '' },
  long: { name: 'CVCV', category: '量', type: '動', named: 'Aは長い', version: 0, etymology: '' },
  thick: { name: 'CVCV', category: '量', type: '動', named: 'Aは厚い', version: 0, etymology: '' },
  wide: { name: 'CVCV', category: '量', type: '動', named: 'Aは幅廣い', version: 0, etymology: '' },

  point: { name: 'CVCV', category: '數學', type: '動', named: 'Aは點', version: 0, etymology: '' },
  line: { name: 'CVCV', category: '數學', type: '動', named: 'Aは線', version: 0, etymology: '' },
  plane: { name: 'CVCV', category: '數學', type: '動', named: 'Aは平面', version: 0, etymology: '' },
  polygon: { name: 'CVCV', category: '數學', type: '動', named: 'Aは多面體', version: 0, etymology: '' },
  sharp: { name: 'CVCV', category: '數學', type: '動', named: 'Aは角', version: 0, etymology: '' },
  centre: { name: 'CVCV', category: '數學', type: '動', named: 'AはBの中心', version: 0, etymology: '' },
  interval: { name: 'CVCV', category: '數學', type: '動', named: 'Aは區間', version: 0, etymology: '' },
  function: { name: 'CVCV', category: '數學', type: '動', named: 'Aは函數', version: 0, etymology: '' },

  space: { name: 'CVCV', category: '物理', type: '動', named: 'Aは空間', version: 0, etymology: '' },
  time: { name: 'CVCV', category: '物理', type: '動', named: 'Aは時間', version: 0, etymology: '' },
  wave: { name: 'CVCV', category: '物理', type: '動', named: 'Aは波', version: 0, etymology: '' },
  particle: { name: 'CVCV', category: '物理', type: '動', named: 'Aは粒子', version: 0, etymology: '' },
  light: { name: 'CVCV', category: '物理', type: '動', named: 'Aは光', version: 0, etymology: '' },
  sound: { name: 'CVCV', category: '物理', type: '動', named: 'Aは音', version: 0, etymology: '' },
  reflect: { name: 'CVCV', category: '物理', type: '動', named: 'AはBを反射する', version: 0, etymology: '' },

  electron: { name: 'CVCV', category: '物理/粒子', type: '動', named: 'Aは電子', version: 0, etymology: '' },
  atom: { name: 'CVCV', category: '物理/粒子', type: '動', named: 'Aは原子', version: 0, etymology: '' },
  molecule: { name: 'CVCV', category: '物理/粒子', type: '動', named: 'Aは分子', version: 0, etymology: '' },

  solid: { name: 'CVCV', category: '物理/態', type: '動', named: 'Aは固體', version: 0, etymology: '' },
  liquid: { name: 'CVCV', category: '物理/態', type: '動', named: 'Aは液體', version: 0, etymology: '' },
  gas: { name: 'CVCV', category: '物理/態', type: '動', named: 'Aは氣體', version: 0, etymology: '' },
  plasma: { name: 'CVCV', category: '物理/態', type: '動', named: 'Aはplasma', version: 0, etymology: '' },

  water: { name: 'CVCV', category: '化學', type: '動', named: 'Aは水', version: 0, etymology: '' },
  salt: { name: 'CVCV', category: '化學', type: '動', named: 'Aは鹽', version: 0, etymology: '' },
  oil: { name: 'CVCV', category: '化學', type: '動', named: 'Aは油脂', version: 0, etymology: '' },
  metal: { name: 'CVCV', category: '化學', type: '動', named: 'Aは金屬', version: 0, etymology: '' },

  colour: { name: 'CVCV', category: '色', type: '動', named: 'AはB色を呈する', version: 0, etymology: '' },
  bright: { name: 'CVCV', category: '色', type: '動', named: 'Aは明るい', version: 0, etymology: '' },
  colourful: { name: 'CVCV', category: '色', type: '動', named: 'Aは高彩度である', version: 0, etymology: '' },
  red: { name: 'CVCV', category: '色', type: '動', named: 'Aは赤い', version: 0, etymology: '' },
  orange: { name: 'CVCV', category: '色', type: '動', named: 'Aは橙色を呈する', version: 0, etymology: '' },
  yellow: { name: 'CVCV', category: '色', type: '動', named: 'Aは黄色を呈する', version: 0, etymology: '' },
  green: { name: 'CVCV', category: '色', type: '動', named: 'Aは綠色を呈する', version: 0, etymology: '' },
  blue: { name: 'CVCV', category: '色', type: '動', named: 'Aは青い', version: 0, etymology: '' },
  purple: { name: 'CVCV', category: '色', type: '動', named: 'Aは紫色を呈する', version: 0, etymology: '' },

  astral: { name: 'nacV', category: '宇宙', type: '動', named: 'Aは天體', version: 0, etymology: 'Ara نجمة' },
  star: { name: 'CVCV', category: '宇宙', type: '動', named: 'Aは恆星', version: 0, etymology: '' },
  planet: { name: 'CVCV', category: '宇宙', type: '動', named: 'Aは惑星', version: 0, etymology: '' },
  sattelite: { name: 'CVCV', category: '宇宙', type: '動', named: 'Aは衞星', version: 0, etymology: '' },

  land: { name: 'hajV', category: '地理', type: '動', named: 'Aは陸', version: 0, etymology: 'Xgn xajar' },
  sky: { name: 'CVCV', category: '地理', type: '動', named: 'Aは空', version: 0, etymology: '' },
  mountain: { name: 'libV', category: '地理', type: '動', named: 'Aは山', version: 0, etymology: 'tibetan རི་བོ' },
  sea: { name: 'CVCV', category: '地理', type: '動', named: 'Aは海', version: 0, etymology: '' },
  lake: { name: 'CVCV', category: '地理', type: '動', named: 'Aは湖', version: 0, etymology: '' },
  river: { name: 'najV', category: '地理', type: '動', named: 'Aは川', version: 0, etymology: 'Ain nay' },

  male: { name: 'namV', category: '性', type: '動', named: 'Aは雄', version: 0, etymology: 'Ltc 男' },
  female: { name: 'vomV', category: '性', type: '動', named: 'Aは雌', version: 0, etymology: 'Ja をみな' },
  copulate: { name: 'kopV', category: '性', type: '動', named: 'AはBと交接する', version: 0, etymology: 'Lat copulare' },

  human: { name: 'CVCV', category: '生物', type: '動', named: 'Aは人', version: 0, etymology: '' },
  animal: { name: 'CVCV', category: '生物', type: '動', named: 'Aは動物', version: 0, etymology: '' },
  plant: { name: 'CVCV', category: '生物', type: '動', named: 'Aは植物', version: 0, etymology: '' },

  hair: { name: 'CVCV', category: '身體/頭', type: '動', named: 'AはBの毛である', version: 0, etymology: '' },
  brain: { name: 'CVCV', category: '身體/頭', type: '動', named: 'AはBの腦である', version: 0, etymology: '' },
  eye: { name: 'CVCV', category: '身體/頭', type: '動', named: 'AはBの目である', version: 0, etymology: '' },
  ear: { name: 'CVCV', category: '身體/頭', type: '動', named: 'AはBの耳である', version: 0, etymology: '' },
  nose: { name: 'CVCV', category: '身體/頭', type: '動', named: 'AはBの鼻である', version: 0, etymology: '' },
  mouth: { name: 'CVCV', category: '身體/頭', type: '動', named: 'AはBの口である', version: 0, etymology: '' },
  tooth: { name: 'CVCV', category: '身體/頭', type: '動', named: 'AはBの齒（牙）である', version: 0, etymology: '' },
  tongue: { name: 'CVCV', category: '身體/頭', type: '動', named: 'AはBの舌である', version: 0, etymology: '' },
  throat: { name: 'CVCV', category: '身體/頭', type: '動', named: 'AはBの喉である', version: 0, etymology: '' },
  horn: { name: 'CVCV', category: '身體/頭', type: '動', named: 'AはBの角である', version: 0, etymology: '' },

  heart: { name: 'CVCV', category: '身體/内臓', type: '動', named: 'AはBの心臓である', version: 0, etymology: '' },
  lung: { name: 'CVCV', category: '身體/内臓', type: '動', named: 'AはBの肺である', version: 0, etymology: '' },
  gut: { name: 'CVCV', category: '身體/内臓', type: '動', named: 'AはBの消化管である', version: 0, etymology: '' },

  trunk: { name: 'CVCV', category: '身體/胴', type: '動', named: 'AはBの胴（幹）である', version: 0, etymology: '' },
  tail: { name: 'CVCV', category: '身體/胴', type: '動', named: 'AはBの尾である', version: 0, etymology: '' },
  ass: { name: 'CVCV', category: '身體/胴', type: '動', named: 'AはBの臀部である', version: 0, etymology: '' },
  penis: { name: 'CVCV', category: '身體/胴', type: '動', named: 'AはBの陰莖（陰核）である', version: 0, etymology: '' },
  womb: { name: 'CVCV', category: '身體/胴', type: '動', named: 'AはBの子宮である', version: 0, etymology: '' },
  nipple: { name: 'CVCV', category: '身體/胴', type: '動', named: 'AはBの乳首である', version: 0, etymology: '' },

  limb: { name: 'CVCV', category: '身體/肢', type: '動', named: 'AはBの肢（腕・脚・枝・翼）である', version: 0, etymology: '' },
  hand: { name: 'CVCV', category: '身體/肢', type: '動', named: 'AはBの手足である', version: 0, etymology: '' },
  finger: { name: 'CVCV', category: '身體/肢', type: '動', named: 'AはBの指である', version: 0, etymology: '' },
  nail: { name: 'CVCV', category: '身體/肢', type: '動', named: 'AはBの爪である', version: 0, etymology: '' },

  nerve: { name: 'CVCV', category: '身體/全身', type: '動', named: 'AはBの神經である', version: 0, etymology: '' },
  muscle: { name: 'CVCV', category: '身體/全身', type: '動', named: 'AはBの肉である', version: 0, etymology: '' },
  bone: { name: 'CVCV', category: '身體/全身', type: '動', named: 'AはBの骨である', version: 0, etymology: '' },
  skin: { name: 'CVCV', category: '身體/全身', type: '動', named: 'AはBの肌である', version: 0, etymology: '' },

  fruit: { name: 'CVCV', category: '身體/植物', type: '動', named: 'AはBの果實である', version: 0, etymology: '' },
  root: { name: 'CVCV', category: '身體/植物', type: '動', named: 'AはBの根である', version: 0, etymology: '' },

  eat: { name: 'kVnV', category: '生理', type: '動', named: 'AはBを食ふ', version: 0, etymology: 'Proto-Tai kɯɲ' },
  digest: { name: 'CVCV', category: '生理', type: '動', named: 'AはBを消化する', version: 0, etymology: '' },
  excrete: { name: 'CVCV', category: '生理', type: '動', named: 'AはBを排泄する', version: 0, etymology: '' },

  sense: { name: 'CVCV', category: '感覺', type: '動', named: 'AはBを感ず', version: 0, etymology: '' },
  hear: { name: 'CVCV', category: '感覺', type: '動', named: 'AはBを聞く', version: 0, etymology: '' },
  see: { name: 'CVCV', category: '感覺', type: '動', named: 'AはBを見る', version: 0, etymology: '' },
  taste: { name: 'CVCV', category: '感覺', type: '動', named: 'AはBを味を感ず', version: 0, etymology: '' },
  smell: { name: 'CVCV', category: '感覺', type: '動', named: 'AはBを匂ひを感ず', version: 0, etymology: '' },
  touch: { name: 'CVCV', category: '感覺', type: '動', named: 'AはBを觸感す', version: 0, etymology: '' },
  hurt: { name: 'CVCV', category: '感覺', type: '動', named: 'AはBを痛む', version: 0, etymology: '' },

  smile: { name: 'CVCV', category: '表情', type: '動', named: 'Aは微笑する', version: 0, etymology: '' },
  laugh: { name: 'CVCV', category: '表情', type: '動', named: 'Aは笑ふ', version: 0, etymology: '' },
  frown: { name: 'CVCV', category: '表情', type: '動', named: 'Aは顔を顰める', version: 0, etymology: '' },
  cry: { name: 'CVCV', category: '表情', type: '動', named: 'AはB（涙）を流す', version: 0, etymology: '' },

  want: { name: 'lVsV', category: '感情', type: '動', named: 'AはBを求める', version: 0, etymology: 'He רצה' },
  glad: { name: 'CVCV', category: '感情', type: '動', named: 'AはBを喜ぶ', version: 0, etymology: '' },
  amuse: { name: 'CVCV', category: '感情', type: '動', named: 'AはBを樂しむ', version: 0, etymology: '' },
  respect: { name: 'CVCV', category: '感情', type: '動', named: 'AはBを敬ふ', version: 0, etymology: '' },
  pride: { name: 'CVCV', category: '感情', type: '動', named: 'AはBを誇る', version: 0, etymology: '' },
  amaze: { name: 'CVCV', category: '感情', type: '動', named: 'AはBに驚く', version: 0, etymology: '' },
  anger: { name: 'CVCV', category: '感情', type: '動', named: 'AはBに怒る', version: 0, etymology: '' },
  threat: { name: 'CVCV', category: '感情', type: '動', named: 'AはBに脅ゆ', version: 0, etymology: '' },

  think: { name: 'kVcV', category: '思考', type: '動', named: 'AはBを思ふ', version: 0, etymology: 'Lat cōgitāre' },
  know: { name: 'dVnV', category: '思考', type: '動', named: 'AはBを知る', version: 0, etymology: 'Fas دانستن' },
  understand: { name: 'CVCV', category: '思考', type: '動', named: 'AはBを理解する', version: 0, etymology: '' },
  assume: { name: 'CVCV', category: '思考', type: '動', named: 'AはBを假定する', version: 0, etymology: '' },
  plan: { name: 'CVCV', category: '思考', type: '動', named: 'AはBを意圖する', version: 0, etymology: '' },
  expect: { name: 'CVCV', category: '思考', type: '動', named: 'AはBを豫期する', version: 0, etymology: '' },
  hope: { name: 'CVCV', category: '思考', type: '動', named: 'AはBを希望する', version: 0, etymology: '' },
  agree: { name: 'CVCV', category: '思考', type: '動', named: 'AはBを同意する', version: 0, etymology: '' },
  deduce: { name: 'CVCV', category: '思考', type: '動', named: 'AはBを推理する', version: 0, etymology: '' },
  aim: { name: 'CVCV', category: '思考', type: '動', named: 'AはBを目的とする', version: 0, etymology: 'Tam நோக்கம்' },

  word: { name: 'locV', category: '言語', type: '動', named: 'Aは詞', version: 0, etymology: 'Grc λόγος' },
  true: { name: 'velV', category: '言語', type: '動', named: 'Aは眞實', version: 0, etymology: 'Lat vērus' },
  speak: { name: 'CVCV', category: '言語', type: '動', named: 'AはBを話す', version: 0, etymology: '' },
  write: { name: 'CVCV', category: '言語', type: '動', named: 'AはBを書く', version: 0, etymology: '' },
  read: { name: { alias: 'WRITE-BACK' }, category: '', type: '動', named: 'AはBを讀む', version: 0, etymology: '' },

  declare: { name: 'CVCV', category: '行動', type: '動', named: 'AはBを宣言する', version: 0, etymology: '' },
  ask: { name: 'CVCV', category: '行動', type: '動', named: 'AはBを質問する', version: 0, etymology: '' },
  apologise: { name: 'CVCV', category: '行動', type: '動', named: 'AはBを謝る', version: 0, etymology: '' },
  appreciate: { name: 'CVCV', category: '行動', type: '動', named: 'AはBを感謝する', version: 0, etymology: '' },
  forgive: { name: 'CVCV', category: '行動', type: '動', named: 'AはBを許す', version: 0, etymology: '' },
  deceive: { name: 'CVCV', category: '行動', type: '動', named: 'AはBだと欺く', version: 0, etymology: '' },

  greet: { name: 'CVCV', category: '行動', type: '動', named: 'Aは挨拶する', version: 0, etymology: '' },
  fight: { name: 'fehV', category: '行動', type: '動', named: 'AはBに抗ふ', version: 0, etymology: 'Gem fehtaną' },

  play: { name: 'ludV', category: '文化', type: '動', named: 'AはBを遊ぶ', version: 0, etymology: 'Lat lūdere' },
  dance: { name: 'palV', category: '文化', type: '動', named: 'AはBを踊る', version: 0, etymology: 'Xcl պար' },
  music: { name: 'musV', category: '文化', type: '動', named: 'AはBを演奏する', version: 0, etymology: 'Grc μοῦσα' },
  intercourse: { name: 'mazV', category: '文化', type: '動', named: '性行爲する', version: 0, etymology: 'Jpn まじはる' },

  building: { name: 'CVCV', category: '文明', type: '動', named: 'Aは建造物', version: 0, etymology: '' },
  town: { name: 'CVCV', category: '文明', type: '動', named: 'Aは町', version: 0, etymology: '' },
  nation: { name: 'CVCV', category: '文明', type: '動', named: 'Aは國', version: 0, etymology: '' },
  group: { name: 'CVCV', category: '文明', type: '動', named: 'Aは集團（會） である', version: 0, etymology: '' },

  world: { name: 'vixV', category: '', type: '動', named: 'Aは世界', version: 0, etymology: 'sanskrit विश्व' },
  begin: { name: 'CVCV', category: '', type: '動', named: 'Aは始まる', version: 0, etymology: '' },
  end: { name: { alias: 'BEGIN-BACK' }, category: '', type: '動', named: 'Aは終はる', version: 0, etymology: '' },
  person: { name: 'pitV', category: '', type: '動', named: 'Aは自我を持つ', version: 0, etymology: 'Jpn ひと' },
  live: { name: 'CVCV', category: '', type: '動', named: 'Aは生きる', version: 0, etymology: '' },
  wake: { name: 'budV', category: '', type: '動', named: 'Aは覺める', version: 0, etymology: 'sanskrit बुध्' },
  old: { name: 'CVCV', category: '', type: '動', named: 'Aは古い', version: 0, etymology: '' },
  rot: { name: 'CVCV', category: '', type: '動', named: 'Aは腐る', version: 0, etymology: '' },
  temporary: { name: 'CVCV', category: '', type: '動', named: 'Aは一時的である', version: 0, etymology: '' },
  unit: { name: 'CVCV', category: '', type: '動', named: 'AはBの最小單位', version: 0, etymology: '' },

  cause: { name: 'qalV', category: '', type: '動', named: 'AはBを起こす', version: 0, etymology: 'San कारण' },
  influence: { name: 'CVCV', category: '', type: '動', named: 'AはBを影響する', version: 0, etymology: '' },
  home: { name: 'CVCV', category: '', type: '動', named: 'AはBを據點とする', version: 0, etymology: '' },
  consume: { name: 'CVCV', category: '', type: '動', named: 'AはBを費やす', version: 0, etymology: '' },
  differ: { name: 'CVCV', category: '', type: '動', named: 'AはBと異なる', version: 0, etymology: '' },
  value: { name: 'CVCV', category: '', type: '動', named: 'AはBに値する', version: 0, etymology: '' },
  make: { name: 'fakV', category: '', type: '動', named: 'AはBを作る', version: 0, etymology: 'Lat facere' },
  leave: { name: 'CVCV', category: '', type: '動', named: 'AはBを去る', version: 0, etymology: '' },
  rotate: { name: 'CVCV', category: '', type: '動', named: 'AはBの周りを回轉する', version: 0, etymology: '' },
  use: { name: 'CVCV', category: '', type: '動', named: 'A（道具・手段）はB（目的）を滿たす', version: 0, etymology: '' },
  model: { name: 'CVCV', category: '', type: '動', named: 'AはBを再現する', version: 0, etymology: '' },
  imitate: { name: 'CVCV', category: '', type: '動', named: 'AはBを模倣する', version: 0, etymology: '' },
  status: { name: 'CVCV', category: '', type: '動', named: 'AはBの狀態である', version: 0, etymology: '' },
  manner: { name: 'CVCV', category: '', type: '動', named: 'AはBの樣態である', version: 0, etymology: '' },
  system: { name: 'CVCV', category: '', type: '動', named: 'Aは系である', version: 0, etymology: '' },

  meter: { name: 'metwlo', category: 'SI單位', type: '動', named: 'Aは1m', version: 0, etymology: 'Eng' },
  second: { name: 'sekudo', category: 'SI單位', type: '動', named: 'Aは1s', version: 0, etymology: 'Eng' },
  kilogram: { name: 'qilocw', category: 'SI單位', type: '動', named: 'Aは1kg', version: 0, etymology: 'Eng' },
  ampere: { name: 'mapele', category: 'SI單位', type: '動', named: 'Aは1A', version: 0, etymology: 'Eng' },
  kelvin: { name: 'kelwvi', category: 'SI單位', type: '動', named: 'Aは1K', version: 0, etymology: 'Eng' },
  candela: { name: 'kadela', category: 'SI單位', type: '動', named: 'Aは1cd', version: 0, etymology: 'Eng' },
}