export const dictBase = {
  der: ['CV', '', '', ''],
  den: ['CV', '', '', ''],
  as: ['CV', '', '', ''],

  _tense: ['CV', '', '', '-:過去, 0:現在, +:未來'],
  _aspect: ['CV', '', '', 'min:開始, max:完了'],

  _connect: ['o', '', '', ''],
  _predicate: ['y', '', '', ''],

  i: ['cen', '代', '述', '我'],
  thou: ['ven', '代', '述', '汝'],
  he: ['sen', '代', '述', '彼'],
  now: ['CVC', '代', '述', '今'],
  here: ['CVC', '代', '述', 'ここ'],
  something: ['CVC', '代', '述', ''],

  what: ['CVr', '', '', ''],
  that: ['CVr', '', '', ''],

  so_much: ['CV', '代', '* 數: 量', '（x:數）ほど'],
  how_much: ['CV', '代', '量', '幾ら'],

  _quote: ['CV', '構造', '借用→述', 'xと呼ばれる'],
  _quote_end: ['CV', '構造', '述→述', ''],

  _past: ['CV', '', '助述', '=WHAT NOW BEFORE-V AT'],

  unrestrictive: ['CV', '述→述', '', '非制限'],
  typical: ['CV', '述→述', '', '習慣'],
  figurative: ['CV', '述→述', '', '譬喩'],

  zero: ['CV', '數字', '數詞', '0'],
  one: ['CV', '數字', '數詞', '1'],
  two: ['CV', '數字', '數詞', '2'],
  three: ['CV', '數字', '數詞', '3'],
  four: ['CV', '數字', '數詞', '4'],
  five: ['CV', '數字', '數詞', '5'],
  six: ['CV', '數字', '數詞', '6'],
  seven: ['CV', '數字', '數詞', '7'],
  eight: ['CV', '數字', '數詞', '8'],
  nine: ['CV', '數字', '數詞', '9'],
  ten: ['CV', '數字', '數詞', '10'],
  eleven: ['CV', '數字', '數詞', '11'],
  twelve: ['CV', '數字', '數詞', '12'],
  thirteen: ['CV', '數字', '數詞', '13'],
  fourteen: ['CV', '數字', '數詞', '14'],
  fifteen: ['CV', '數字', '數詞', '15'],

  exp: ['CV', '數字/記號', '數詞', 'E'],

  null: ['CV', '特殊數字', '數詞', '無'],
  min: ['CV', '特殊數字', '數詞', '最小'],
  max: ['CV', '特殊數字', '數詞', '最大'],

  at_most: ['CV', '特殊數字/關係', '數詞', '≤'],
  less_than: ['CV', '特殊數字/關係', '數詞', '<'],

  negative: ['CV', '特殊數字', '數詞', '=LESS_THAN ZERO'],
  positive: ['CV', '特殊數字', '數詞', '=ZERO LESS_THAN'],

  aleph0: ['CV', '特殊數字', '無限', '可算無限'],
  aleph1: ['CV', '特殊數字', '無限', '非可算無限'],

  tau: ['CV', '定數', '數詞', 'τ=6.283+ε'],
  napier: ['CV', '定數', '數詞', 'e=2.718+ε'],

  normal: ['CV', '特殊數字', '數詞', '通常の'],
  high: ['CV', '特殊數字', '數詞', '[別名] MORE NORMAL'],
  low: ['CV', '特殊數字', '數詞', '[別名] PASSIVE MORE NORMAL'],

  plus: ['CV', '演算', '數詞', '+'],
  minus: ['CV', '演算', '數詞', '-'],
  multiply: ['CV', '演算', '數詞', '*'],
  divide: ['CV', '演算', '數詞', '/'],
  modulo: ['CV', '演算', '數詞', '%'],
  power: ['CV', '演算', '數詞', '^'],
  logarithm: ['CV', '演算', '數詞', 'log'],

  ordinal: ['CV', '數字', '數→述', 'aはx番目である'],

  not: ['CV', '', '', ''],
  and: ['CV', '', '', ''],
  or: ['CV', '', '', ''],
  imply: ['CV', '', '', ''],

  back: ['CVC', '', '述', 'aはbの逆である'],

  have: ['CVC', '', '述', '有す'],
  give: ['CVC', '', '述', '與ふ'],
  take: [{ translate: 'GIVE-_CONNECT-BACK' }, '', '述', '受く'],

  below: ['CVC', '位置關係', '述', 'AはBの下に有る'],
  behind: ['CVC', '位置關係', '述', 'AはBの後に有る'],
  left: ['CVC', '位置關係', '述', 'EはDの左に有る'],
  before: ['CVC', '位置關係', '述', 'AはBより前に有る'],

  far: ['CVC', '位置關係/複雜', '述', 'aはbから遠い'],
  cross: ['CVC', '位置關係/複雜', '述', 'aはbに交叉する'],
  orthogonal: ['CVC', '位置關係/複雜', '述', 'aはbに直交する'],
  parallel: ['CVC', '位置關係/複雜', '述', 'aはbに平行する'],

  big: ['CVC', '量', '述', '大きい'],
  long: ['CVC', '量', '述', '長い'],
  thick: ['CVC', '量', '述', '厚い'],
  wide: ['CVC', '量', '述', '幅廣い'],

  point: ['CVC', '數學', '述', '點'],
  line: ['CVC', '數學', '述', '線'],
  plane: ['CVC', '數學', '述', '平面'],
  polygon: ['CVC', '數學', '述', '多面體'],
  sharp: ['CVC', '數學', '述', '角'],
  centre: ['CVC', '數學', '述', 'aはbの中心'],
  interval: ['CVC', '數學', '述', '區間'],
  function: ['CVC', '數學', '述', '函數'],

  space: ['CVC', '物理', '述', '空間'],
  time: ['CVC', '物理', '述', '時間'],
  wave: ['CVC', '物理', '述', '波'],
  particle: ['CVC', '物理', '述', '粒子'],
  light: ['CVC', '物理', '述', '光'],
  sound: ['CVC', '物理', '述', '音'],
  reflect: ['CVC', '物理', '述', 'aはbを反射する'],

  elementary_particle: ['CVC', '物理/粒子', '述', '素粒子'],
  electron: ['CVC', '物理/粒子', '述', '電子'],
  atom: ['CVC', '物理/粒子', '述', '原子'],
  molecule: ['CVC', '物理/粒子', '述', '分子'],

  solid: ['CVC', '物理/態', '述', '固體'],
  liquid: ['CVC', '物理/態', '述', '液體'],
  gas: ['CVC', '物理/態', '述', '氣體'],
  plasma: ['CVC', '物理/態', '述', 'plasma'],

  salt: ['CVC', '化學', '述', '鹽'],
  oil: ['CVC', '化學', '述', '油脂'],

  colour: ['CVC', '色', '述', 'aはb色を呈する'],
  bright: ['CVC', '色', '述', '明るい'],
  colourful: ['CVC', '色', '述', '高彩度である'],
  red: ['CVC', '色', '述', '赤い'],
  orange: ['CVC', '色', '述', '橙色を呈する'],
  yellow: ['CVC', '色', '述', '黄色を呈する'],
  green: ['CVC', '色', '述', '綠色を呈する'],
  blue: ['CVC', '色', '述', '青い'],
  purple: ['CVC', '色', '述', '紫色を呈する'],

  universe: ['CVC', '宇宙', '述', '宇宙'],
  star: ['CVC', '宇宙', '述', '恆星'],
  planet: ['CVC', '宇宙', '述', '惑星'],
  sattelite: ['CVC', '宇宙', '述', '衞星'],

  land: ['CVC', '地理', '述', '陸'],
  sky: ['CVC', '地理', '述', '空'],
  mountain: ['CVC', '地理', '述', '山'],
  sea: ['CVC', '地理', '述', '海'],
  lake: ['CVC', '地理', '述', '湖'],
  river: ['CVC', '地理', '述', '川'],

  male: ['CVC', '性', '述', '雄'],
  female: ['CVC', '性', '述', '雌'],
  copulate: ['CVC', '性', '述', 'aはbと交接する'],

  human: ['CVC', '生物', '述', '人'],
  animal: ['CVC', '生物', '述', '動物'],
  plant: ['CVC', '生物', '述', '植物'],

  hair: ['CVC', '身體/頭', '述', 'bはaの毛である'],
  brain: ['CVC', '身體/頭', '述', 'bはaの腦である'],
  eye: ['CVC', '身體/頭', '述', 'bはaの目である'],
  ear: ['CVC', '身體/頭', '述', 'bはaの耳である'],
  nose: ['CVC', '身體/頭', '述', 'bはaの鼻である'],
  mouth: ['CVC', '身體/頭', '述', 'bはaの口である'],
  tooth: ['CVC', '身體/頭', '述', 'bはaの齒（牙）である'],
  tongue: ['CVC', '身體/頭', '述', 'bはaの舌である'],
  throat: ['CVC', '身體/頭', '述', 'bはaの喉である'],
  horn: ['CVC', '身體/頭', '述', 'bはaの角である'],

  heart: ['CVC', '身體/内臓', '述', 'bはaの心臓である'],
  lung: ['CVC', '身體/内臓', '述', 'bはaの肺である'],
  gut: ['CVC', '身體/内臓', '述', 'bはaの消化管である'],

  trunk: ['CVC', '身體/胴', '述', 'bはaの胴（幹）である'],
  tail: ['CVC', '身體/胴', '述', 'bはaの尾である'],
  ass: ['CVC', '身體/胴', '述', 'bはaの臀部である'],
  penis: ['CVC', '身體/胴', '述', 'bはaの陰莖（陰核）である'],
  womb: ['CVC', '身體/胴', '述', 'bはaの子宮である'],
  nipple: ['CVC', '身體/胴', '述', 'bはaの乳首である'],

  limb: ['CVC', '身體/肢', '述', 'bはaの肢（腕・脚・枝・翼）である'],
  hand: ['CVC', '身體/肢', '述', 'bはaの手足である'],
  finger: ['CVC', '身體/肢', '述', 'bはaの指である'],
  nail: ['CVC', '身體/肢', '述', 'bはaの爪である'],

  nerve: ['CVC', '身體/全身', '述', 'bはaの神經である'],
  muscle: ['CVC', '身體/全身', '述', 'bはaの肉である'],
  bone: ['CVC', '身體/全身', '述', 'bはaの骨である'],
  skin: ['CVC', '身體/全身', '述', 'bはaの肌である'],

  fruit: ['CVC', '身體/植物', '述', 'bはaの果實である'],
  root: ['CVC', '身體/植物', '述', 'bはaの根である'],

  eat: ['CVC', '生理', '述', 'aはbを食ふ'],
  digest: ['CVC', '生理', '述', 'aはbを消化する'],
  excrete: ['CVC', '生理', '述', 'aはbを排泄する'],

  sense: ['CVC', '感覺', '述', 'aはbを感ず'],
  hear: ['CVC', '感覺', '述', 'aはbを聞く'],
  see: ['CVC', '感覺', '述', 'aはbを見る'],
  taste: ['CVC', '感覺', '述', 'aはbの味を感ず'],
  smell: ['CVC', '感覺', '述', 'aはbの匂ひを感ず'],
  touch: ['CVC', '感覺', '述', 'aはbを觸感す'],
  hurt: ['CVC', '感覺', '述', 'aはbに痛む'],

  smile: ['CVC', '表情', '述', '微笑する'],
  laugh: ['CVC', '表情', '述', '笑ふ'],
  frown: ['CVC', '表情', '述', '顔を顰める'],
  cry: ['CVC', '表情', '述', 'aはb（涙）を流す'],

  want: ['CVC', '感情', '述', 'EはDを求める'],
  glad: ['CVC', '感情', '述', '喜ぶ'],
  amuse: ['CVC', '感情', '述', '樂しむ'],
  respect: ['CVC', '感情', '述', '敬ふ'],
  pride: ['CVC', '感情', '述', '誇る'],
  amaze: ['CVC', '感情', '述', '驚く'],
  anger: ['CVC', '感情', '述', '怒る'],
  threat: ['CVC', '感情', '述', '脅𛀁る'],

  think: ['CVC', '思考', '述', 'GはEを思ふ'],
  know: ['CVC', '思考', '述', 'GはEを知る'],
  understand: ['CVC', '思考', '述', 'GはEを理解する'],
  assume: ['CVC', '思考', '述', 'GはEを假定する'],
  plan: ['CVC', '思考', '述', 'GはEを意圖する'],
  expect: ['CVC', '思考', '述', 'GはEを豫期する'],
  hope: ['CVC', '思考', '述', 'GはEを希望する'],
  agree: ['CVC', '思考', '述', 'GはEに同意する'],
  deduce: ['CVC', '思考', '述', 'GはEを推理する'],

  word: ['CVC', '言語', '述', '詞'],
  sentence: ['CVC', '言語', '述', '文（命題）'],
  true: ['CVC', '言語', '述', '眞實'],
  speak: ['CVC', '言語', '述', 'GはEを話す'],
  write: ['CVC', '言語', '述', 'GはEをDに書く'],

  declare: ['CVC', '行動', '述', 'aはbを宣言する'],
  ask: ['CVC', '行動', '述', 'aはbを質問する'],
  greet: ['CVC', '行動', '述', '挨拶する'],
  apologise: ['CVC', '行動', '述', 'aはbについて謝る'],
  appreciate: ['CVC', '行動', '述', 'aはbについて感謝する'],
  forgive: ['CVC', '行動', '述', 'aはbについて許す'],
  fight: ['CVC', '行動', '述', 'aはbに抗ふ'],
  deceive: ['CVC', '行動', '述', 'aはbであると欺く'],

  play: ['CVC', '文化', '述', 'aはbを遊ぶ'],
  dance: ['CVC', '文化', '述', 'aはbを踊る'],
  music: ['CVC', '文化', '述', 'aはbを演奏する'],
  intercourse: ['CVC', '文化', '述', '性行爲する'],

  building: ['CVC', '文明', '述', '建造物'],
  town: ['CVC', '文明', '述', '町'],
  nation: ['CVC', '文明', '述', '國'],
  group: ['CVC', '文明', '述', 'aはbを目的とするの集團（會） である'],

  world: ['CVC', '', '述', '世界'],
  begin: ['CVC', '', '述', '始まる'],
  end: [{ translate: 'BEGIN-_CONNECT-BACK' }, '', '述', '終はる'],
  person: ['CVC', '', '述', '自我を持つ'],
  live: ['CVC', '', '述', '生きる'],
  wake: ['CVC', '', '述', '覺める'],
  old: ['CVC', '', '述', '古い'],
  rot: ['CVC', '', '述', '腐る'],
  temporary: ['CVC', '', '述', '一時的である'],

  cause: ['CVC', '', '述', 'aはbを起こす'],
  influence: ['CVC', '', '述', 'aはbに影響する'],
  home: ['CVC', '', '述', 'aはbを據點とする'],
  consume: ['CVC', '', '述', 'aはbを費やす'],
  differ: ['CVC', '', '述', 'aはbと異なる'],
  value: ['CVC', '', '述', 'aはbに値する'],
  make: ['CVC', '', '述', 'aはbを作る'],
  contain: ['CVC', '', '述', 'aはbを含む'],
  leave: ['CVC', '', '述', 'aはbから去る'],
  rotate: ['CVC', '', '述', 'aはbの周りを回轉する'],
  use: ['CVC', '', '述', 'G（道具・手段）をEはD（目的）に使ふ'],
  model: ['CVC', '', '述', 'AはBを再現する'],
  imitate: ['CVC', '', '述', 'AはBを模倣する'],
  status: ['CVC', '', '述', 'AはBの狀態である'],
  manner: ['CVC', '', '述', 'AはBの樣態である'],

  meter: ['meter', 'SI單位', '述', '[借用] 1m'],
  second: ['sekun', 'SI單位', '述', '[借用] 1s'],
  kilogram: ['kilol', 'SI單位', '述', '[借用] 1kg'],
  ampere: ['hapel', 'SI單位', '述', '[借用] 1A'],
  kelvin: ['kevin', 'SI單位', '述', '[借用] 1K'],
  candela: ['kadel', 'SI單位', '述', '[借用] 1cd'],
}