const toHexRoman = n =>
  n.toString(16)
    .replace(/F/ig, 'O')
    .replace(/E/ig, 'X')
    .replace(/D/ig, 'N')
    .replace(/C/ig, 'M')
    .replace(/B/ig, 'L')
    .replace(/A/ig, 'K')
    .replace(/9/g, 'I')
    .replace(/8/g, 'Y')
    .replace(/7/g, 'H')
    .replace(/6/g, 'Z')
    .replace(/5/g, 'F')
    .replace(/4/g, 'E')
    .replace(/3/g, 'D')
    .replace(/2/g, 'C')
    .replace(/1/g, 'B')
    .replace(/0/g, 'A')
